[package]
name = "mozlz4"
version = "0.1.0"
authors = ["Justin Wong <jusw85@hotmail.com>", "Mitchell Ferree <thebeatbutton@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.30"
byteorder = "1"
mozlz4-sys = { path = "mozlz4-sys" }
